<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />

    <div class="form-group">
        <label for="refresh-rate" class="group-name"><?= _t('ext.auto_refresh.refresh_rate'); ?></label>
        <div class="group-controls">
            <input type="number" name="refresh-rate" id="refresh-rate" min="1" value="<?= $this->getRefreshRate() ?>">
        </div>
    </div>

    <div class="form-group form-actions">
        <div class="group-controls">
            <button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
            <button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
        </div>
    </div>
</form>
